kind: Pod
metadata:
  name: pod #The name of the Kubernetes pod to be created in the Kubernetes cluster
  namespace: ali
  labels:
    app: hellonode-app
spec:
  containers:
  - name: hellonode-app #The name of the react.js application container
    image: samirtata/hellonode:latest #The Docker image for building the React.js application container
    ports:
    - containerPort: 8000 #The port for the node.js application container
